### ISSUE TITLE
Does shine support collocation of "MGT"/MDT?

### ISSUE THREAD

**Issue by barthe** [cea-hpc/shine#207]
Looking at the code a target is either MGT or MDT.
Do you confirm that shine is not able to manage FS using collocated MGT/MDT?

Regards, Benj

**Comment by degremont** [comment]
Indeed, Shine does not support a device containing both a MGS and a MDT.

(This configuration is now deprecated by Lustre for a while.)

**Comment by barthe** [comment]
ok!
It is still often used in the documentation (it's simpler for lustre example) and I did not see any notes about this being deprecated. Only a little warning that it will obviously limit the MGS to handle only one FS. 
It works without any warning in 2.10.5 LTS release.
Anyway it was to make a demo of shine ;-), I wanted to be sure that I was not missing an option, I will use 2 dedicated devices !

Thanks Aurelien !
